# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

shared: &shared
  bare_metal_server_ip: <%= ENV['BARE_METAL_SERVER_IP'] %>
  bare_metal_server_user: <%= ENV['BARE_METAL_SERVER_USER'] %>
  bare_metal_server_password: <%= ENV['BARE_METAL_SERVER_PASSWORD'] %>
  heroku_api_key: <%= ENV['HEROKU_API_KEY'] %>
  github_api: <%= ENV["GITHUB_API"] %>
  github_password: <%= ENV["GITHUB_PASSWORD"] %>

development:
  <<: *shared
  api_name: 'development'
  api_password: '12345'
  admin_password: '12345'
  secret_key_base: 836fa3665997a860728bcb9e9a1e704d427cfc920e79d847d79c8a9a907b9e965defa4154b2b86bdec6930adbe33f21364523a6f6ce363865724549fdfc08553

test:
  <<: *shared
  api_name: 'test'
  api_password: '12345'
  secret_key_base: 5a37811464e7d378488b0f073e2193b093682e4e21f5d6f3ae0a4e1781e61a351fdc878a843424e81c73fb484a40d23f92c8dafac4870e74ede6e5e174423010

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *shared
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_name: <%= ENV["API_NAME"] %>
  api_password: <%= ENV["API_PASSWORD"] %>
  ga: <%= ENV["GA"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
